name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '.github/workflows/bump.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate OpenAPI spec
        uses: swagger-api/validator-action@v3
        with:
          files: docs/api-documentation.yml

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: lms
          token: ${{ secrets.BUMP_TOKEN }}
          file: docs/api-documentation.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Comment PR with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: lms
          token: ${{ secrets.BUMP_TOKEN }}
          file: docs/api-documentation.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
